### ISSUE TITLE
CPU on Mini-8 100% When Parser Is Marked Active

### ISSUE THREAD

**Issue by gary-hammer** [pjpeartree/rainmachine-gw1000#2]
The CPU usage value on my Mini-8 pegs at 100% and everything (populating logs, weather, etc) is extremely slow.
Disable this parser all returns to normal.

**Comment by pjpeartree** [comment]
@gary-hammer thank you for reporting this issue.
Can you test it with the newer version?
I have reduced the arithmetic effort by using cumulative numerical total divided by the number of observations.

Fixed by https://github.com/pjpeartree/rainmachine-ecowitt/commit/e1cfad2bc8cf3571117181558b9dca595899aa4a
